"""Long-lived AgentStrata Gateway protocol and durable state primitives."""

from .approvals import GatewayApprovalService, GatewayApprovalStore

from .application import (
    CLIENT_CHANNEL,
    GatewayApplicationError,
    GatewaySessionService,
    SessionPage,
    client_account,
    conversation_authority_ref,
    is_gateway_admin,
)

from .channels import (
    ApplicationIngressPort,
    ChannelRuntimeError,
    ChannelRuntimeHealth,
    ChannelRuntimeManager,
    ChannelRuntimeState,
    DeliveryEventSinkPort,
)
from .coordinator import (
    ActorTurnExecutorPort,
    ChannelOutboundPort,
    GatewayTurnCoordinator,
    GatewayTurnCoordinatorError,
)
from .dispatcher import GatewayApplicationDispatcher
from .events import (
    GatewayEventPublisher,
    GatewaySessionEventVisibility,
    LiveEventSink,
)

from .protocol import (
    GATEWAY_EVENTS,
    GATEWAY_METHODS,
    GATEWAY_SCOPES,
    PROTOCOL_MAX_VERSION,
    PROTOCOL_MIN_VERSION,
    GatewayCredentialAuthority,
    GatewayCredentialBinding,
    GatewayHandshakeAuthority,
    GatewayProtocolError,
    StaticGatewayCredentialAuthority,
    decode_frame,
    encode_frame,
    request_fingerprint,
    validate_request_access,
)
from .server import (
    GatewayClientContext,
    GatewayDispatchError,
    GatewayEventVisibilityPolicy,
    GatewayMutationReconciliation,
    GatewayPublishResult,
    GatewayReplayBatch,
    GatewayRequestDispatcher,
    GatewayServerConfig,
    GatewayServerHealth,
    GatewayServerLifecycleError,
    GatewayWebSocketServer,
)
from .state_store import (
    ApprovalConflict,
    ApprovalRecord,
    AuthorizationDecisionRecord,
    GatewayEventRecord,
    GatewayEventReplay,
    GatewayStateError,
    GatewayStateStore,
    IdempotencyConflict,
    IdempotencyReservation,
    IngressConflict,
    IngressRecord,
    IngressReservation,
    OutboundConflict,
    OutboundRecord,
    RunConflict,
    RunOutcome,
    RunRecord,
    RunState,
    SessionConflict,
    SessionRecord,
    StaleWriterGeneration,
)

__all__ = [
    "ApprovalConflict",
    "ApprovalRecord",
    "AuthorizationDecisionRecord",
    "ActorTurnExecutorPort",
    "ApplicationIngressPort",
    "CLIENT_CHANNEL",
    "ChannelOutboundPort",
    "ChannelRuntimeError",
    "ChannelRuntimeHealth",
    "ChannelRuntimeManager",
    "ChannelRuntimeState",
    "DeliveryEventSinkPort",
    "GATEWAY_EVENTS",
    "GATEWAY_METHODS",
    "GATEWAY_SCOPES",
    "PROTOCOL_MAX_VERSION",
    "PROTOCOL_MIN_VERSION",
    "GatewayCredentialAuthority",
    "GatewayCredentialBinding",
    "GatewayHandshakeAuthority",
    "GatewayProtocolError",
    "GatewayClientContext",
    "GatewayApplicationDispatcher",
    "GatewayApplicationError",
    "GatewayDispatchError",
    "GatewayEventVisibilityPolicy",
    "GatewayMutationReconciliation",
    "GatewayApprovalService",
    "GatewayApprovalStore",
    "GatewayEventRecord",
    "GatewayEventPublisher",
    "GatewayEventReplay",
    "GatewayPublishResult",
    "GatewayReplayBatch",
    "GatewayRequestDispatcher",
    "GatewaySessionEventVisibility",
    "GatewaySessionService",
    "GatewayServerConfig",
    "GatewayServerHealth",
    "GatewayServerLifecycleError",
    "GatewayStateError",
    "GatewayStateStore",
    "GatewayWebSocketServer",
    "IdempotencyConflict",
    "IdempotencyReservation",
    "IngressConflict",
    "IngressRecord",
    "IngressReservation",
    "OutboundConflict",
    "OutboundRecord",
    "RunConflict",
    "RunOutcome",
    "RunRecord",
    "RunState",
    "SessionPage",
    "SessionConflict",
    "SessionRecord",
    "StaticGatewayCredentialAuthority",
    "StaleWriterGeneration",
    "GatewayTurnCoordinator",
    "GatewayTurnCoordinatorError",
    "LiveEventSink",
    "client_account",
    "conversation_authority_ref",
    "decode_frame",
    "encode_frame",
    "request_fingerprint",
    "is_gateway_admin",
    "validate_request_access",
]
