#!/usr/bin/env bash
# write_env.sh — 控制台「写机密」按钮背后的唯一 sh 入口（首次部署向导 step1）。
#
# 把实例机密 + 派生路径原子写入 env 文件并 chmod 600。键值经 stdin 传入，
# 格式为每行 `KEY=<base64(value)>`：
#   - 走 stdin 而非 argv，机密不出现在进程命令行（防 `ps` 泄露）。
#   - value 先 base64 编码，规避换行 / 引号 / 空格的 shell 转义问题。
# 调用方（console.control.operations）负责算好派生路径与键顺序，本脚本只落盘，
# 不重复实现路径推导逻辑。
#
# 用法：
#   printf 'FEISHU_APP_ID=%s\n' "$(printf %s "$val" | base64 -w0)" | bash write_env.sh ~/.chatcopilot-x.env
#
# 退出码：0 成功；2 参数错误；1 写入失败。
set -uo pipefail

ENV_FILE="${1:-}"
if [ -z "$ENV_FILE" ]; then
    echo "[ERR] 用法：bash write_env.sh <env_file>（键值经 stdin 传 KEY=base64(value)）" >&2
    exit 2
fi

case "$ENV_FILE" in
    "~") ENV_FILE="$HOME" ;;
    "~/"*) ENV_FILE="$HOME/${ENV_FILE#"~/"}" ;;
esac

dir="$(dirname "$ENV_FILE")"
if ! mkdir -p "$dir" 2>/dev/null; then
    echo "[ERR] 无法创建目录：$dir" >&2
    exit 1
fi

tmp="$(mktemp "${ENV_FILE}.XXXXXX")" || { echo "[ERR] mktemp 失败" >&2; exit 1; }
trap 'rm -f "$tmp"' EXIT
chmod 600 "$tmp" 2>/dev/null || true

{
    echo "# AgentStrata secret config (generated by console)"
    echo
    while IFS= read -r line || [ -n "$line" ]; do
        [ -z "$line" ] && continue
        key="${line%%=*}"
        b64="${line#*=}"
        # 仅接受合法 env 键名，挡住畸形输入。
        case "$key" in
            [A-Za-z_][A-Za-z0-9_]*) ;;
            *) echo "[ERR] 非法键名：$key" >&2; exit 1 ;;
        esac
        if ! value="$(printf %s "$b64" | base64 -d 2>/dev/null)"; then
            echo "[ERR] base64 解码失败：$key" >&2
            exit 1
        fi
        # 单引号包裹，内部单引号转义为 '\'' —— 完全杜绝 shell 注入。
        escaped="${value//\'/\'\\\'\'}"
        echo "export ${key}='${escaped}'"
    done
} > "$tmp" || exit 1

if ! mv -f "$tmp" "$ENV_FILE"; then
    echo "[ERR] 移动到目标失败：$ENV_FILE" >&2
    exit 1
fi
trap - EXIT
chmod 600 "$ENV_FILE" 2>/dev/null || true
echo "[OK] 已写入 $ENV_FILE (chmod 600)"
