"""Shared contracts for AgentStrata layers.

This package is the only allowed dependency target for DTOs and lightweight
ports shared by agent, botspec, platforms, middleware, and external tools.
It must stay independent from those higher-level packages.
"""
from __future__ import annotations

from chatcopilot.contracts.agent import (
    AgentEvent,
    AgentResult,
    AgentTask,
    DeferredLifecycleIntent,
    EventSink,
    FinalText,
    LlmCallStarted,
    LlmCallFinished,
    ResourceRef,
    SpanFinished,
    SpanStarted,
    TextDelta,
    ToolFinished,
    ToolStarted,
    TopicDecisionMade,
    TurnError,
)
from chatcopilot.contracts.identity import (
    AssistantMode,
    Identity,
    Role,
    SessionIdentity,
    role_ge,
    role_value,
)
from chatcopilot.contracts.model_selection import (
    CODE_MODEL_LANE,
    CODEX_REASONING_EFFORTS,
    CodeModelProfile,
    CodeModelSelection,
    MODEL_SELECTION_SCOPE_ONCE,
    MODEL_SELECTION_SCOPE_SESSION,
    MODEL_SELECTION_SOURCE_DEFAULT,
    MODEL_SELECTION_SOURCE_PROFILE,
)
from chatcopilot.contracts.development import (
    DevelopmentTaskScope,
    current_development_task_scope,
    development_task_scope,
    parse_write_scope,
)
from chatcopilot.contracts.code_tasks import (
    CODE_TASK_ACTIVE_STATUSES,
    CODE_TASK_RESUMABLE_STATUSES,
    CODE_TASK_TERMINAL_STATUSES,
    CODE_TASK_TOOL,
    CodeTaskAttempt,
    CodeTaskLimits,
    CodeTaskStatus,
)
from chatcopilot.contracts.skills import SkillIndexEntry, read_skill_body, render_skill_index_section
from chatcopilot.contracts.subagents import (
    BUILTIN_SUBAGENT_PRESET_NAMES,
    BUILTIN_SUBAGENT_WORKFLOW_NAMES,
    BUILTIN_SUBAGENT_WORKFLOWS,
    CachePolicySpec,
    ContextPolicySpec,
    CustomSubagentSpec,
    PromptLayerSpec,
    SearchProviderSpec,
    SubagentBudgetSpec,
    SubagentDef,
    SubagentSpec,
    ToolMatchRule,
    ToolSelectorSpec,
    WorkflowDef,
)
from chatcopilot.contracts.runtime import (
    AgentRuntimePlan,
    BotRuntimePlan,
    McpPlan,
    McpServerConfig,
    RagSourceConfig,
    RagSourcePlan,
    SubagentBudgetPlan,
    SubagentPlan,
)
from chatcopilot.contracts.tool_packs import (
    ToolFeatureEntry,
    ToolModuleBinding,
    ToolPackEntry,
    ToolPackPrompt,
)
from chatcopilot.contracts.tools import (
    EXECUTION_GLOBAL_SERIAL_BACKGROUND,
    EXECUTION_SYNC,
    EXECUTION_USER_SERIAL_BACKGROUND,
    DocAnchors,
    Handler,
    HandlerResult,
    ToolContext,
    ToolDef,
    ToolHandlerError,
    build_mcp_schema,
    build_openai_schema,
    properties_from_argparse,
)
from chatcopilot.contracts.workspace import WorkspaceRef, WorkspaceView

__all__ = [
    "AgentEvent",
    "AgentResult",
    "AgentRuntimePlan",
    "AgentTask",
    "AssistantMode",
    "BUILTIN_SUBAGENT_PRESET_NAMES",
    "BUILTIN_SUBAGENT_WORKFLOW_NAMES",
    "BUILTIN_SUBAGENT_WORKFLOWS",
    "BotRuntimePlan",
    "CODE_MODEL_LANE",
    "CODEX_REASONING_EFFORTS",
    "CODE_TASK_ACTIVE_STATUSES",
    "CODE_TASK_RESUMABLE_STATUSES",
    "CODE_TASK_TERMINAL_STATUSES",
    "CODE_TASK_TOOL",
    "CodeTaskAttempt",
    "CodeTaskLimits",
    "CodeTaskStatus",
    "CodeModelProfile",
    "CodeModelSelection",
    "DeferredLifecycleIntent",
    "DevelopmentTaskScope",
    "DocAnchors",
    "EXECUTION_GLOBAL_SERIAL_BACKGROUND",
    "EXECUTION_SYNC",
    "EXECUTION_USER_SERIAL_BACKGROUND",
    "EventSink",
    "FinalText",
    "Handler",
    "HandlerResult",
    "Identity",
    "LlmCallStarted",
    "LlmCallFinished",
    "McpPlan",
    "MODEL_SELECTION_SCOPE_ONCE",
    "MODEL_SELECTION_SCOPE_SESSION",
    "MODEL_SELECTION_SOURCE_DEFAULT",
    "MODEL_SELECTION_SOURCE_PROFILE",
    "RagSourcePlan",
    "ResourceRef",
    "Role",
    "SearchProviderSpec",
    "SessionIdentity",
    "SpanFinished",
    "SpanStarted",
    "CustomSubagentSpec",
    "McpServerConfig",
    "RagSourceConfig",
    "SubagentBudgetSpec",
    "SubagentSpec",
    "SubagentBudgetPlan",
    "SubagentPlan",
    "TextDelta",
    "ToolContext",
    "ToolFeatureEntry",
    "ToolModuleBinding",
    "ToolPackEntry",
    "ToolPackPrompt",
    "ToolDef",
    "ToolHandlerError",
    "ToolFinished",
    "ToolStarted",
    "TopicDecisionMade",
    "TurnError",
    "WorkspaceRef",
    "WorkspaceView",
    "CachePolicySpec",
    "ContextPolicySpec",
    "PromptLayerSpec",
    "SkillIndexEntry",
    "SubagentDef",
    "ToolMatchRule",
    "ToolSelectorSpec",
    "WorkflowDef",
    "read_skill_body",
    "render_skill_index_section",
    "build_mcp_schema",
    "build_openai_schema",
    "current_development_task_scope",
    "development_task_scope",
    "parse_write_scope",
    "properties_from_argparse",
    "role_ge",
    "role_value",
]
