#!/usr/bin/env python3
"""Generate compatibility requirements files from ``pyproject.toml``."""
from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Any

try:
    import tomllib  # type: ignore[attr-defined]
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib  # type: ignore[no-redef]


ROOT = Path(__file__).resolve().parents[1]
Target = tuple[bool, tuple[str, ...], frozenset[str] | None]
TARGETS: dict[str, Target] = {
    "requirements.txt": (False, ("desktop",), None),
    "src/chatcopilot/agent/requirements.txt": (True, ("agent",), None),
    "src/chatcopilot/middleware/acp/requirements.txt": (True, ("agent", "acp"), None),
    "console/requirements.txt": (
        True,
        ("console",),
        None,
    ),
}
HEADER = (
    "# Generated by scripts/sync_requirements.py from pyproject.toml.\n"
    "# Do not edit this file directly.\n\n"
)


def _metadata() -> dict[str, Any]:
    return tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))


def _distribution_name(requirement: str) -> str:
    match = re.match(r"[A-Za-z0-9][A-Za-z0-9._-]*", requirement)
    if match is None:
        raise ValueError(f"invalid dependency requirement: {requirement!r}")
    return re.sub(r"[-_.]+", "-", match.group(0)).lower()


def rendered_requirements() -> dict[Path, str]:
    project = _metadata()["project"]
    core = tuple(str(item) for item in project.get("dependencies", ()))
    groups = project.get("optional-dependencies", {})
    rendered: dict[Path, str] = {}
    for rel_path, (include_core, names, selected_names) in TARGETS.items():
        entries: list[str] = list(core if include_core else ())
        found_names: set[str] = set()
        for name in names:
            if name not in groups:
                raise KeyError(f"missing optional dependency group: {name}")
            group_entries = tuple(str(item) for item in groups[name])
            if selected_names is not None:
                group_entries = tuple(
                    item
                    for item in group_entries
                    if _distribution_name(item) in selected_names
                )
                found_names.update(_distribution_name(item) for item in group_entries)
            entries.extend(group_entries)
        if selected_names is not None and found_names != set(selected_names):
            missing = ", ".join(sorted(set(selected_names) - found_names))
            raise KeyError(f"missing selected dependencies for {rel_path}: {missing}")
        rendered[ROOT / rel_path] = HEADER + "\n".join(dict.fromkeys(entries)) + "\n"
    return rendered


def check() -> list[str]:
    drift: list[str] = []
    for path, expected in rendered_requirements().items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            drift.append(str(path.relative_to(ROOT)))
    return drift


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    args = parser.parse_args()
    if args.check:
        drift = check()
        if drift:
            print("requirements drift: " + ", ".join(drift))
            return 1
        print("OK: generated requirements")
        return 0
    for path, content in rendered_requirements().items():
        path.write_text(content, encoding="utf-8")
        print(f"updated {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
